# The base URL of the site.
base_url = "https://jackyliu16.github.io"

# To avoid problems with some variables due to multilingual support,
# you will find repeated variables in the language section,
# it is recommended that you keep those of your language and the general
# ones with the same data.
default_language = "en"
theme = "ataraxia"

# To find a detailed description of the following configuration variables
# you can go to https://www.getzola.org/documentation/getting-started/configuration/

output_dir = "public"

build_search_index = true
generate_feed = true
feed_filename = "atom.xml"
# feed_limit = 20

compile_sass = false

minify_html = false
hard_link_static = false

# ignored_content = []


[extra]
    author = "jackyliu16"

    # Use a square image (same height as width)
    avatar = "images/avatar.png"

    # To use a favicon convert your image to https://realfavicongenerator.net/,
    # then download and copy the package to static/images/favicon
    favicon = true
    locale = "es_CO"

    # Ataraxia uses Bootstrap icons,
    # you can go to https://icons.getbootstrap.com/ to find the full list
    [extra.menus]
        nav = [
            { name = "Main", url = "@/_index.md", icon = "bi-house" },
            { name = "Blog", url = "@/blog/_index.md", icon = "bi-file-earmark-text" },
            { name = "Projects", url = "@/projects/_index.md", icon = "bi-terminal" },
            { name = "Tags", url = "tags", icon = "bi-bookmarks" }
        ]
    
    [extra.social]
        author_link = "https://github.com/jackyliu16"
        twitter = "@gersonbdev"
        links = [
            { name = "Email", url = "onedragon424@foxmail.com", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/jackyliu16", icon = "bi-github" },
            # { name = "LinkedIn", url = "https://www.linkedin.com/in/gersonbenavides/", icon = "bi-linkedin" },
            # { name = "Twitter", url = "https://twitter.com/gersonbdev", icon = "bi-twitter" },
            # { name = "Facebook", url = "https://www.facebook.com/gersonbdev/", icon = "bi-facebook" },
            # { name = "Instagram", url = "https://www.instagram.com/gersonbdev/", icon = "bi-instagram" }
        ]

    [extra.seo]
        google_analytics = "G-K6X2LLGGLY"
        # google_search_console = ""
    [extra.comments]
        disqus = "gersonbdev"

    [extra.copyright]
        name = "CC BY 4.0"
        url = "https://creativecommons.org/licenses/by/4.0/"


[languages]
    [languages.en]
        title = "jackyliu16's website"
        description = "Projects, ideas, technologies"
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]

    [languages.en.translations]
        post = "Post"
        category = "Category"
        tag = "Tag"
        search = "Search"

        404_message = "Page not found"

        by = "By"
        posted = "Posted"
        updated = "Updated"
        categories = "Categories"
        tags = "Tags"
        share = "Share"
      
        next = "Next"
        previous = "Previous"

        short_copyright = "Some rights reserved."
        full_copyright = """\
            Except where otherwise noted, the blog posts on this site are \
            licensed under the Creative Commons Attribution 4.0 International \
            (CC BY 4.0) License by the author.\
            """

    [languages.zh]
        title = "刘某人的记录小站"
        description = "项目，意见，技术等"
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]

    [languages.zh.translations]
        post = "Post"
        category = "Category"
        tag = "Tag"
        search = "Search"

        404_message = "Page not found"

        by = "By"
        posted = "Posted"
        updated = "Updated"
        categories = "Categories"
        tags = "Tags"
        share = "Share"
      
        next = "Next"
        previous = "Previous"

        short_copyright = "Some rights reserved."
        full_copyright = """\
            Except where otherwise noted, the blog posts on this site are \
            licensed under the Creative Commons Attribution 4.0 International \
            (CC BY 4.0) License by the author.\
            """


[markdown]
    highlight_code = true
    # extra_syntaxes_and_themes = []
    highlight_theme = "gruvbox-dark"

    render_emoji = true


    external_links_target_blank = true  # Whether external links are to be opened in a new tab
    external_links_no_follow = true     # Whether to set rel="nofollow" for all external links
    external_links_no_referrer = true   # Whether to set rel="noreferrer" for all external links

    smart_punctuation = false           # Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)


[search]
    include_title = true
    include_description = false
    include_path = false
    include_content = true
    # truncate_content_length = 100


[link_checker]
    # Skip link checking for external URLs that start with these prefixes
    # skip_prefixes = []
    # Skip anchor checking for external URLs that start with these prefixes
    # skip_anchor_prefixes = []

    internal_level = "error"
    external_level = "error"


[slugify]
    paths = "on"
    taxonomies = "on"
    anchors = "on"

    # When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
    paths_keep_dates = false